openapi: 3.0.0
servers:
  - url: https://petstore.swagger.io/v2
    description: Default server
  - url: https://petstore.swagger.io/sandbox
    description: Sandbox server

info:
  title: Pet Store
  version: 1.0.0