query-issue-list = '''
    query($ghp_username:String!, $ghp_repository:String!, $ghp_issue_states:[IssueState!]!, $ghp_labels:[String!]!) {
        repository(owner: $ghp_username, name: $ghp_repository) {
            issues(labels: $ghp_labels, states: $ghp_issue_states, filterBy: { assignee: $ghp_username }, first: 10) {
                nodes {
                    number,
                    id,
                    url,
                    title,
                    body
                }
            }
        }
    }
'''

query-issue-comments = '''
    query($ghp_username:String!, $ghp_repository:String!, $ghp_issue_states:[IssueState!]!, $ghp_labels:[String!]!) {
        repository(owner: $ghp_username, name: $ghp_repository) {
            issues(labels: $ghp_labels, states: $ghp_issue_states, filterBy: { assignee: $ghp_username }, first: 20) {
                nodes {
                    number,
                    id,
                    url,
                    title,
                    body,
                    publishedAt,
                    labels(first: 10) {
                        nodes {
                            name
                        }
                    },
                    comments(first: 100) {
                        nodes {
                            databaseId,
                            id,
                            url,
                            body,
                            publishedAt
                        }
                    }
                }
            }
        }
    }
'''

get-issue-details = '''
    query($ghp_username:String!, $ghp_repository:String!, $issue_number:Int!) {
        repository(owner: $ghp_username,name: $ghp_repository) {
            issue(number: $issue_number) {
                id,
                number,
                url,
                title,
                body
            }
        }
    }
'''