[headr]

[[headr.navi]]
label = '首页'
link = '/'

[[headr.navi]]
label = '博客'
link = '/blog'

[[headr.navi]]
label = '笔记'
link = '/notebook'

[[headr.navi]]
label = '关于'
link = '/about'


[footer]

[footer.sitemap]
label = '站点地图'

[[footer.sitemap.links]]
label = '博客'
link = '/blog'

[[footer.sitemap.links]]
label = '笔记'
link = '/kits/notebook'

[[footer.sitemap.links]]
label = '动态页面'
link = '/page/list'

[footer.kits]
label = '常用工具'

[[footer.kits.links]]
label = '比较文本'
link = '/kits/editor/difference'

[[footer.kits.links]]
label = '变色龙'
link = '/kits/editor/chameleon'

[footer.social]
label = '友情链接'

[[footer.social.links]]
label = '此间·我们'
link = 'https://cijian.us'
